### ISSUE TITLE
cursor color not same as text color

### ISSUE THREAD

**Issue by mrigdon** [mattboldt/typed.js#204]
For some reason the cursor color is not changing when I change the css `color`.

HTML:
```html
<div class="col-md-12">
    <span id="typed"></span>
</div>
```
CSS:
```css
#typed {
    color: white;
    display: inline;
  }
```

Screenshot:
<img width="213" alt="typed" src="https://cloud.githubusercontent.com/assets/7377110/20114581/b6405d38-a5a9-11e6-86b4-26c52880cb69.png">

It's subtle but notice the dark gray cursor
